version: '3'
services: 
    main:
        container_name: main
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
            - .env.example:/var/www/.env

        ports:
            - 8000:80
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - application
        depends_on:
            - db
    db:
        container_name: db
        image: mariadb
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MARIADB_DATABASE=task
            - MARIADB_PASSWORD=root
            - MARIADB_ROOT_PASSWORD=root
            - MARIADB_ALLOW_EMPTY_PASSWORD=true
        restart: always
        networks:
            - application
networks:
    application:
        driver: bridge
volumes:
    db_data:
        driver: local